networks:
  flink-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    networks:
      - flink-network
    ports:
      - "2181:2181"

#  hbase:
#    image: blueskyareahm/hbase-base:2.1.3
#    container_name: hbase
#    command: master
#    networks:
#      - flink-network
#    ports:
#      - "16000:16000"
#      - "16010:16010"
#      - "16201:16201"
#      - "16301:16301"
#    environment:
#      - HBASE_ZOOKEEPER_QUORUM=zookeeper:2181
#      - HBASE_MANAGES_ZK=false
#    depends_on:
#      - zookeeper
#    volumes:
#      - ./init-script.hbase:/init-script.hbase


  hbase-master:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    container_name: hbase-master
    networks:
      - flink-network
    ports:
      - "16000:16000"  # Puerto de servicio del HBase Master
      - "16010:16010"
    volumes:
      - ./init-script.hbase:/init-script.hbase
      - ./hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper:2181
      - HBASE_MANAGES_ZK=false
      - HBASE_CONF_DIR=/opt/hbase/conf
    depends_on:
      - zookeeper
      - hbase-region
    command: [ "hbase", "master", "start" ]

  hbase-region:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    container_name: hbase-region
    networks:
      - flink-network
    ports:
      - "16020:16020"  # Puerto de servicio del HBase RegionServer
      - "16030:16030"
    volumes:
    - ./init-script.hbase:/init-script.hbase
    - ./hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    environment:
      - HBASE_ZOOKEEPER_QUORUM=zookeeper:2181
      - HBASE_MANAGES_ZK=false
      - HBASE_CONF_DIR=/opt/hbase/conf
    depends_on:
      - zookeeper
    command: ["hbase", "regionserver", "start"]

  jobmanager:
    build:
      context: ./flinkbase
    container_name: jobmanager
    networks:
      - flink-network
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    depends_on:
      - zookeeper
      - hbase-master

  taskmanager:
    build:
      context: ./flinkbase  
    container_name: taskmanager
    networks:
      - flink-network
    command: taskmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    depends_on:
      - jobmanager
      - hbase-master