networks:
  flink-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    networks:
      - flink-network
    ports:
      - "2181:2181"

  hbase:
    build:
      context: ./hbase
      dockerfile: Dockerfile
    container_name: hbase
    command: "/opt/hbase/bin/hbase master start"
    networks:
      - flink-network
    ports:
      - "16000:16000"
      - "16010:16010"
    environment:
      - JAVA_HOME=/usr/local/openjdk-8
      - HBASE_ZOOKEEPER_QUORUM=zookeeper:2181
      - HBASE_MANAGES_ZK=false
    volumes:
      - ./init-script.hbase:/init-script.hbase
      - ./hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    depends_on:
      - zookeeper

  jobmanager:
    build:
      context: ./flinkbase
    container_name: jobmanager
    mem_limit: 4g
    networks:
      - flink-network
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    depends_on:
      - zookeeper
      - hbase

  taskmanager:
    build:
      context: ./flinkbase
    container_name: taskmanager
    mem_limit: 4g
    networks:
      - flink-network
    command: taskmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    depends_on:
      - jobmanager
      - hbase